import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class apiBase {
  url: string = 'https://192.168.137.1:5001';
  Ws: string;
  libros = [
    {
      Id: '448',
      Nombre: 'English A1',
      NombreArchivo: 'HSC_A1_englsih_a1',
      Idioma: 'Ingles',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'High School',
    },
    {
      Id: '449',
      Nombre: 'English A2',
      NombreArchivo: 'HSC_A2_englsih_a2',
      Idioma: 'Ingles',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'High School',
    },
    {
      Id: '450',
      Nombre: 'English B1',
      NombreArchivo: 'HSC_B1_english_b1',
      Idioma: 'Ingles',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'High School',
    },
    {
      Id: '451',
      Nombre: 'English B2',
      NombreArchivo: 'HSC_B2_english_b2',
      Idioma: 'Ingles',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '452',
      Nombre: 'English C1',
      NombreArchivo: 'HSC_C1_englsih_c1',
      Idioma: 'Ingles',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '453',
      Nombre: 'Ética I',
      NombreArchivo: 'HSC_01_etica_I',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'High School',
    },
    {
      Id: '454',
      Nombre: 'Matemáticas I',
      NombreArchivo: 'HSC_01_matematicas_I',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'High School',
    },
    {
      Id: '455',
      Nombre: 'Metodología de la Investigación',
      NombreArchivo: 'HSC_01_metodologia_de_la_investigacion',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'High School',
    },
    {
      Id: '456',
      Nombre: 'Química I',
      NombreArchivo: 'HSC_01_quimica_I',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'High School',
    },
    {
      Id: '457',
      Nombre: 'Taller de Lectura y Redacción',
      NombreArchivo: 'HSC_01_taller_de_lectura_y_redaccion',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'High School',
    },
    {
      Id: '458',
      Nombre: 'Investigation Methodology',
      NombreArchivo: 'HSC_01_investigation_methodology',
      Idioma: 'Ingles',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'High School',
    },
    {
      Id: '459',
      Nombre: 'Ética II',
      NombreArchivo: 'HSC_02_etica_II',
      Idioma: 'Espanol',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'High School',
    },
    {
      Id: '460',
      Nombre: 'Introducción a las Ciencias Sociales',
      NombreArchivo: 'HSC_02_introduccion_a_las_ciencias_sociales',
      Idioma: 'Espanol',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'High School',
    },
    {
      Id: '461',
      Nombre: 'Matemáticas II',
      NombreArchivo: 'HSC_02_matematicas_II',
      Idioma: 'Espanol',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'High School',
    },
    {
      Id: '462',
      Nombre: 'Química II',
      NombreArchivo: 'HSC_02_quimica_II',
      Idioma: 'Espanol',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'High School',
    },
    {
      Id: '463',
      Nombre: 'Taller de Lectura y Redacción',
      NombreArchivo: 'HSC_02_taller_de_lectura_y_redaccion',
      Idioma: 'Espanol',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'High School',
    },
    {
      Id: '464',
      Nombre: 'Biología I',
      NombreArchivo: 'HSC_03_biologia_I',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'High School',
    },
    {
      Id: '465',
      Nombre: 'Física I',
      NombreArchivo: 'HSC_03_fisica_I',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'High School',
    },
    {
      Id: '466',
      Nombre: 'Historia de México',
      NombreArchivo: 'HSC_03_historia_de_mexico',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'High School',
    },
    {
      Id: '467',
      Nombre: 'Literatura I',
      NombreArchivo: 'HSC_03_literatura_I',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'High School',
    },
    {
      Id: '468',
      Nombre: 'Matemáticas III',
      NombreArchivo: 'HSC_03_matematicas_III',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'High School',
    },
    {
      Id: '469',
      Nombre: 'History of Mexico',
      NombreArchivo: 'HSC_03_history_of_mexico',
      Idioma: 'Ingles',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'High School',
    },
    {
      Id: '470',
      Nombre: 'Biología II',
      NombreArchivo: 'HSC_04_biologia_II',
      Idioma: 'Espanol',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '471',
      Nombre: 'Física II',
      NombreArchivo: 'HSC_04_fisica_II',
      Idioma: 'Espanol',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '472',
      Nombre: 'Historia de México II',
      NombreArchivo: 'HSC_04_historia_de_mexico_II',
      Idioma: 'Espanol',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '473',
      Nombre: 'Literatura II',
      NombreArchivo: 'HSC_04_literatura_II',
      Idioma: 'Espanol',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '474',
      Nombre: 'Matemáticas IV',
      NombreArchivo: 'HSC_04_matematicas_IV',
      Idioma: 'Espanol',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '475',
      Nombre: 'History of Mexico II',
      NombreArchivo: 'HSC_04_history_of_mexico_II',
      Idioma: 'Ingles',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '476',
      Nombre: 'Administración',
      NombreArchivo: 'HSC_05_administracion',
      Idioma: 'Espanol',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '477',
      Nombre: 'Cálculo Diferencial',
      NombreArchivo: 'HSC_05_calculo_diferencial',
      Idioma: 'Espanol',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '478',
      Nombre: 'Contabilidad',
      NombreArchivo: 'HSC_05_contabilidad',
      Idioma: 'Espanol',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '479',
      Nombre: 'Estructura Socioeconomica de México',
      NombreArchivo: 'HSC_05_estructura_socioeconomica_de_mexico',
      Idioma: 'Espanol',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '480',
      Nombre: 'Geografía',
      NombreArchivo: 'HSC_05_geografia',
      Idioma: 'Espanol',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '481',
      Nombre: 'Probabilidad y Estadística',
      NombreArchivo: 'HSC_05_probabilidad_y_estadistica',
      Idioma: 'Espanol',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '482',
      Nombre: 'Geography',
      NombreArchivo: 'HSC_05_geography',
      Idioma: 'Ingles',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '483',
      Nombre: 'Administración II',
      NombreArchivo: 'HSC_06_administracion_II',
      Idioma: 'Espanol',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '484',
      Nombre: 'Cálculo Integral',
      NombreArchivo: 'HSC_06_calculo_integral',
      Idioma: 'Espanol',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '485',
      Nombre: 'Contabilidad II',
      NombreArchivo: 'HSC_06_contabilidad_II',
      Idioma: 'Espanol',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '486',
      Nombre: 'Ecología y Medio Ambiente',
      NombreArchivo: 'HSC_06_ecologia_y_medio_ambiente',
      Idioma: 'Espanol',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '487',
      Nombre: 'Filosofía',
      NombreArchivo: 'HSC_06_filosofia',
      Idioma: 'Espanol',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '488',
      Nombre: 'Historia Universal Contemporánea',
      NombreArchivo: 'HSC_06_historia_universal_contemporanea',
      Idioma: 'Espanol',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '489',
      Nombre: 'Probabilidad y Estadística II',
      NombreArchivo: 'HSC_06_probabilidad_y_estadistica_II',
      Idioma: 'Espanol',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '490',
      Nombre: 'Ecology and Recycling',
      NombreArchivo: 'HSC_06_ecology_and_recycling',
      Idioma: 'Ingles',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '491',
      Nombre: 'Lectoescritura',
      NombreArchivo: 'KIN_01_lectoescritura',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Kinder',
    },
    {
      Id: '492',
      Nombre: 'Matemáticas',
      NombreArchivo: 'KIN_01_matematicas',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Kinder',
    },
    {
      Id: '493',
      Nombre: 'English',
      NombreArchivo: 'KIN_01_english',
      Idioma: 'Ingles',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Kinder',
    },
    {
      Id: '494',
      Nombre: 'Lectoescritura',
      NombreArchivo: 'KIN_02_lectoescritura',
      Idioma: 'Espanol',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Kinder',
    },
    {
      Id: '495',
      Nombre: 'Matemáticas',
      NombreArchivo: 'KIN_02_matematicas',
      Idioma: 'Espanol',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Kinder',
    },
    {
      Id: '496',
      Nombre: 'English',
      NombreArchivo: 'KIN_02_english',
      Idioma: 'Ingles',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Kinder',
    },
    {
      Id: '497',
      Nombre: 'Lectoescritura',
      NombreArchivo: 'KIN_03_lectoescritura',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Kinder',
    },
    {
      Id: '498',
      Nombre: 'Matemáticas',
      NombreArchivo: 'KIN_03_matematicas',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Kinder',
    },
    {
      Id: '499',
      Nombre: 'English',
      NombreArchivo: 'KIN_03_english',
      Idioma: 'Ingles',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Kinder',
    },
    {
      Id: '500',
      Nombre: 'Conocimiento del Medio',
      NombreArchivo: 'ESC_01_conocimiento_del_medio',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '501',
      Nombre: 'Educación Socioemocional',
      NombreArchivo: 'ESC_01_educacion_socioemocional',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '502',
      Nombre: 'Lengua Materna Espanol',
      NombreArchivo: 'ESC_01_lengua_materna_espanol',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '503',
      Nombre: 'Matemáticas',
      NombreArchivo: 'ESC_01_matematicas',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '504',
      Nombre: 'English',
      NombreArchivo: 'ESC_01_english',
      Idioma: 'Ingles',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '505',
      Nombre: 'Math',
      NombreArchivo: 'ESC_01_math',
      Idioma: 'Ingles',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '506',
      Nombre: 'Science',
      NombreArchivo: 'ESC_01_science',
      Idioma: 'Ingles',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '507',
      Nombre: 'Conocimiento del Medio',
      NombreArchivo: 'ESC_02_conocimiento_del_medio',
      Idioma: 'Espanol',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '508',
      Nombre: 'Educación Socioemocional',
      NombreArchivo: 'ESC_02_educacion_socioemocional',
      Idioma: 'Espanol',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '509',
      Nombre: 'Lengua Materna Espanol',
      NombreArchivo: 'ESC_02_lengua_materna_espanol',
      Idioma: 'Espanol',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '510',
      Nombre: 'Matemáticas',
      NombreArchivo: 'ESC_02_matematicas',
      Idioma: 'Espanol',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '511',
      Nombre: 'English',
      NombreArchivo: 'ESC_02_english',
      Idioma: 'Ingles',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '512',
      Nombre: 'Math',
      NombreArchivo: 'ESC_02_math',
      Idioma: 'Ingles',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '513',
      Nombre: 'Science',
      NombreArchivo: 'ESC_02_science',
      Idioma: 'Ingles',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '514',
      Nombre: 'Ciencias Naturales',
      NombreArchivo: 'ESC_03_ciencias_naturales',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '515',
      Nombre: 'Español',
      NombreArchivo: 'ESC_03_espanol',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '516',
      Nombre: 'Formación Cívica y Ética',
      NombreArchivo: 'ESC_03_formacion_civica_y_etica',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '517',
      Nombre: 'Matemáticas',
      NombreArchivo: 'ESC_03_matematicas',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '518',
      Nombre: 'English',
      NombreArchivo: 'ESC_03_english',
      Idioma: 'Ingles',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '519',
      Nombre: 'Math',
      NombreArchivo: 'ESC_03_math',
      Idioma: 'Ingles',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '520',
      Nombre: 'Science',
      NombreArchivo: 'ESC_03_science',
      Idioma: 'Ingles',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '521',
      Nombre: 'Ciencias Naturales',
      NombreArchivo: 'ESC_04_ciencias_naturales',
      Idioma: 'Espanol',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '522',
      Nombre: 'Español',
      NombreArchivo: 'ESC_04_espanol',
      Idioma: 'Espanol',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '523',
      Nombre: 'Formación Cívica y Ética',
      NombreArchivo: 'ESC_04_formacion_civica_y_etica',
      Idioma: 'Espanol',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '524',
      Nombre: 'Geografía',
      NombreArchivo: 'ESC_04_geografia',
      Idioma: 'Espanol',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '525',
      Nombre: 'Historia',
      NombreArchivo: 'ESC_04_historia',
      Idioma: 'Espanol',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '526',
      Nombre: 'Matemáticas',
      NombreArchivo: 'ESC_04_matematicas',
      Idioma: 'Espanol',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '527',
      Nombre: 'English',
      NombreArchivo: 'ESC_04_english',
      Idioma: 'Ingles',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '528',
      Nombre: 'Geography',
      NombreArchivo: 'ESC_04_geography',
      Idioma: 'Ingles',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '529',
      Nombre: 'History',
      NombreArchivo: 'ESC_04_history',
      Idioma: 'Ingles',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '530',
      Nombre: 'Math',
      NombreArchivo: 'ESC_04_math',
      Idioma: 'Ingles',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '531',
      Nombre: 'Science',
      NombreArchivo: 'ESC_04_science',
      Idioma: 'Ingles',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '532',
      Nombre: 'Ciencias Naturales',
      NombreArchivo: 'ESC_05_ciencias_naturales',
      Idioma: 'Espanol',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '533',
      Nombre: 'Español',
      NombreArchivo: 'ESC_05_espanol',
      Idioma: 'Espanol',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '534',
      Nombre: 'Formación Cívica y Ética',
      NombreArchivo: 'ESC_05_formacion_civica_y_etica',
      Idioma: 'Espanol',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '535',
      Nombre: 'Geografía',
      NombreArchivo: 'ESC_05_geografia',
      Idioma: 'Espanol',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '536',
      Nombre: 'Historia',
      NombreArchivo: 'ESC_05_historia',
      Idioma: 'Espanol',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '537',
      Nombre: 'Matemáticas',
      NombreArchivo: 'ESC_05_matematicas',
      Idioma: 'Espanol',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '538',
      Nombre: 'English',
      NombreArchivo: 'ESC_05_english',
      Idioma: 'Ingles',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '539',
      Nombre: 'Geography',
      NombreArchivo: 'ESC_05_geography',
      Idioma: 'Ingles',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '540',
      Nombre: 'History',
      NombreArchivo: 'ESC_05_history',
      Idioma: 'Ingles',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '541',
      Nombre: 'Math',
      NombreArchivo: 'ESC_05_math',
      Idioma: 'Ingles',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '542',
      Nombre: 'Science',
      NombreArchivo: 'ESC_05_science',
      Idioma: 'Ingles',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '543',
      Nombre: 'Ciencias Naturales',
      NombreArchivo: 'ESC_06_ciencias_naturales',
      Idioma: 'Espanol',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '544',
      Nombre: 'Español',
      NombreArchivo: 'ESC_06_espanol',
      Idioma: 'Espanol',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '545',
      Nombre: 'Formación Cívica y Ética',
      NombreArchivo: 'ESC_06_formacion_civica_y_etica',
      Idioma: 'Espanol',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '546',
      Nombre: 'Geografía',
      NombreArchivo: 'ESC_06_geografia',
      Idioma: 'Espanol',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '547',
      Nombre: 'Historia',
      NombreArchivo: 'ESC_06_historia',
      Idioma: 'Espanol',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '548',
      Nombre: 'Matemáticas',
      NombreArchivo: 'ESC_06_matematicas',
      Idioma: 'Espanol',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '549',
      Nombre: 'English',
      NombreArchivo: 'ESC_06_english',
      Idioma: 'Ingles',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '550',
      Nombre: 'Geography',
      NombreArchivo: 'ESC_06_geography',
      Idioma: 'Ingles',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '551',
      Nombre: 'History',
      NombreArchivo: 'ESC_06_history',
      Idioma: 'Ingles',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '552',
      Nombre: 'Math',
      NombreArchivo: 'ESC_06_math',
      Idioma: 'Ingles',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '553',
      Nombre: 'Science',
      NombreArchivo: 'ESC_06_science',
      Idioma: 'Ingles',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '554',
      Nombre: 'Ciencias y Tecnología (Biología)',
      NombreArchivo: 'JHS_01_ciencias_y_tecnologia_biologia',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '555',
      Nombre: 'Formación Cívica y Ética',
      NombreArchivo: 'JHS_01_formacion_civica_y_etica',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '556',
      Nombre: 'Lengua Materna Español',
      NombreArchivo: 'JHS_01_lengua_materna_espanol',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '557',
      Nombre: 'Geography',
      NombreArchivo: 'JHS_01_geography',
      Idioma: 'Ingles',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '558',
      Nombre: 'History',
      NombreArchivo: 'JHS_01_history',
      Idioma: 'Ingles',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '559',
      Nombre: 'Math',
      NombreArchivo: 'JHS_01_math',
      Idioma: 'Ingles',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '560',
      Nombre: 'Ciencias (Física)',
      NombreArchivo: 'JHS_02_ciencias_fisica',
      Idioma: 'Espanol',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '561',
      Nombre: 'Español',
      NombreArchivo: 'JHS_02_espanol',
      Idioma: 'Espanol',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '562',
      Nombre: 'Formación Cívica y Ética',
      NombreArchivo: 'JHS_02_formacion_civica_y_etica',
      Idioma: 'Espanol',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '563',
      Nombre: 'History',
      NombreArchivo: 'JHS_02_history',
      Idioma: 'Ingles',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '564',
      Nombre: 'Math',
      NombreArchivo: 'JHS_02_math',
      Idioma: 'Ingles',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '565',
      Nombre: 'Ciencias (Química)',
      NombreArchivo: 'JHS_03_ciencias_quimica',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '566',
      Nombre: 'Español',
      NombreArchivo: 'JHS_03_espanol',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '567',
      Nombre: 'Formación Cívica y Ética',
      NombreArchivo: 'JHS_03_formacion_civica_y_etica',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '568',
      Nombre: 'History',
      NombreArchivo: 'JHS_03_history',
      Idioma: 'Ingles',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '569',
      Nombre: 'Math',
      NombreArchivo: 'JHS_03_math',
      Idioma: 'Ingles',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '571',
      Nombre: 'English A1',
      NombreArchivo: 'JHS_A1_englsih_a1',
      Idioma: 'Ingles',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '572',
      Nombre: 'English A2',
      NombreArchivo: 'JHS_A2_englsih_a2',
      Idioma: 'Ingles',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '573',
      Nombre: 'English B1',
      NombreArchivo: 'JHS_B1_english_b1',
      Idioma: 'Ingles',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '574',
      Nombre: 'English B2',
      NombreArchivo: 'JHS_B2_english_b2',
      Idioma: 'Ingles',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '575',
      Nombre: 'English C1',
      NombreArchivo: 'JHS_C1_english_c1',
      Idioma: 'Ingles',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '579',
      Nombre: 'Lectoescritura Libro para el Maestro',
      NombreArchivo: 'KIN_TB_01_lectoescritura',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Kinder',
    },
    {
      Id: '580',
      Nombre: 'Matemáticas Libro para el Maestro',
      NombreArchivo: 'KIN_TB_01_matematicas',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Kinder',
    },
    {
      Id: '581',
      Nombre: 'English Teacher´s Book',
      NombreArchivo: 'KIN_TB_01_english',
      Idioma: 'Ingles',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Kinder',
    },
    {
      Id: '582',
      Nombre: 'Lectoescritura Libro para el Maestro',
      NombreArchivo: 'KIN_TB_02_lectoescritura',
      Idioma: 'Espanol',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Kinder',
    },
    {
      Id: '583',
      Nombre: 'Matemáticas Libro para el Maestro',
      NombreArchivo: 'KIN_TB_02_matematicas',
      Idioma: 'Espanol',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Kinder',
    },
    {
      Id: '584',
      Nombre: 'English Teacher´s Book',
      NombreArchivo: 'KIN_TB_02_english',
      Idioma: 'Ingles',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Kinder',
    },
    {
      Id: '585',
      Nombre: 'Lectoescritura Libro para el Maestro',
      NombreArchivo: 'KIN_TB_03_lectoescritura',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Kinder',
    },
    {
      Id: '586',
      Nombre: 'Matemáticas Libro para el Maestro',
      NombreArchivo: 'KIN_TB_03_matematicas',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Kinder',
    },
    {
      Id: '587',
      Nombre: 'English Teacher´s Book',
      NombreArchivo: 'KIN_TB_03_english',
      Idioma: 'Ingles',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Kinder',
    },
    {
      Id: '588',
      Nombre: 'Conocimiento del Medio Libro para el Maestro',
      NombreArchivo: 'ESC_TB_01_conocimiento_del_medio',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '589',
      Nombre: 'Educación Socioemocional Libro para el Maestro',
      NombreArchivo: 'ESC_TB_01_educacion_socioemocional',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '590',
      Nombre: 'Lengua Materna Español Libro para el Maestro',
      NombreArchivo: 'ESC_TB_01_lengua_materna_espanol',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '591',
      Nombre: 'Matemáticas Libro para el Maestro',
      NombreArchivo: 'ESC_TB_01_matematicas',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '592',
      Nombre: 'English Teacher´s Book',
      NombreArchivo: 'ESC_TB_01_english',
      Idioma: 'Ingles',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '593',
      Nombre: 'Math Teacher´s Book',
      NombreArchivo: 'ESC_TB_01_math',
      Idioma: 'Ingles',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '594',
      Nombre: 'Science Teacher´s Book',
      NombreArchivo: 'ESC_TB_01_science',
      Idioma: 'Ingles',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '595',
      Nombre: 'Conocimiento del Medio Libro para el Maestro',
      NombreArchivo: 'ESC_TB_02_conocimiento_del_medio',
      Idioma: 'Espanol',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '596',
      Nombre: 'Educación Socioemocional Libro para el Maestro',
      NombreArchivo: 'ESC_TB_02_educacion_socioemocional',
      Idioma: 'Espanol',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '597',
      Nombre: 'Lengua Materna Espanol Libro para el Maestro',
      NombreArchivo: 'ESC_TB_02_lengua_materna_espanol',
      Idioma: 'Espanol',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '598',
      Nombre: 'Matemáticas',
      NombreArchivo: 'ESC_TB_02_matematicas',
      Idioma: 'Espanol',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '599',
      Nombre: 'English Teacher´s Book',
      NombreArchivo: 'ESC_TB_02_english',
      Idioma: 'Ingles',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '600',
      Nombre: 'Math Teacher´s Book',
      NombreArchivo: 'ESC_TB_02_math',
      Idioma: 'Ingles',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '601',
      Nombre: 'Science Teacher´s Book',
      NombreArchivo: 'ESC_TB_02_science',
      Idioma: 'Ingles',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '602',
      Nombre: 'Ciencias Naturales Libro para el Maestro',
      NombreArchivo: 'ESC_TB_03_ciencias_naturales',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '603',
      Nombre: 'Español Libro para el Maestro',
      NombreArchivo: 'ESC_TB_03_espanol',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '604',
      Nombre: 'Formación Cívica y Ética Libro para el Maestro',
      NombreArchivo: 'ESC_TB_03_formacion_civica_y_etica',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '605',
      Nombre: 'Matemáticas Libro para el Maestro',
      NombreArchivo: 'ESC_TB_03_matematicas',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '606',
      Nombre: 'English Teacher´s Book',
      NombreArchivo: 'ESC_TB_03_english',
      Idioma: 'Ingles',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '607',
      Nombre: 'Math Teacher´s Book',
      NombreArchivo: 'ESC_TB_03_math',
      Idioma: 'Ingles',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '608',
      Nombre: 'Science Teacher´s Book',
      NombreArchivo: 'ESC_TB_03_science',
      Idioma: 'Ingles',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '609',
      Nombre: 'Ciencias Naturales Libro para el Maestro',
      NombreArchivo: 'ESC_TB_04_ciencias_naturales',
      Idioma: 'Espanol',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '610',
      Nombre: 'Español Libro para el Maestro',
      NombreArchivo: 'ESC_TB_04_espanol',
      Idioma: 'Espanol',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '611',
      Nombre: 'Formación Cívica y Ética Libro para el Maestro',
      NombreArchivo: 'ESC_TB_04_formacion_civica_y_etica',
      Idioma: 'Espanol',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '612',
      Nombre: 'Geografía Libro para el Maestro',
      NombreArchivo: 'ESC_TB_04_geografia',
      Idioma: 'Espanol',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '613',
      Nombre: 'Historia Libro para el Maestro',
      NombreArchivo: 'ESC_TB_04_historia',
      Idioma: 'Espanol',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '614',
      Nombre: 'Matemáticas Libro para el Maestro',
      NombreArchivo: 'ESC_TB_04_matematicas',
      Idioma: 'Espanol',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '615',
      Nombre: 'English Teacher´s Book',
      NombreArchivo: 'ESC_TB_04_english',
      Idioma: 'Ingles',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '616',
      Nombre: 'Geography Teacher´s Book',
      NombreArchivo: 'ESC_TB_04_geography',
      Idioma: 'Ingles',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '617',
      Nombre: 'History Teacher´s Book',
      NombreArchivo: 'ESC_TB_04_history',
      Idioma: 'Ingles',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '618',
      Nombre: 'Math Teacher´s Book',
      NombreArchivo: 'ESC_TB_04_math',
      Idioma: 'Ingles',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '619',
      Nombre: 'Science Teacher´s Book',
      NombreArchivo: 'ESC_TB_04_science',
      Idioma: 'Ingles',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '620',
      Nombre: 'Ciencias Naturales Libro para el Maestro',
      NombreArchivo: 'ESC_TB_05_ciencias_naturales',
      Idioma: 'Espanol',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '621',
      Nombre: 'Español Libro para el Maestro',
      NombreArchivo: 'ESC_TB_05_espanol',
      Idioma: 'Espanol',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '622',
      Nombre: 'Formación Cívica y Ética Libro para el Maestro',
      NombreArchivo: 'ESC_TB_05_formacion_civica_y_etica',
      Idioma: 'Espanol',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '623',
      Nombre: 'Geografía Libro para el Maestro',
      NombreArchivo: 'ESC_TB_05_geografia',
      Idioma: 'Espanol',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '624',
      Nombre: 'Historia Libro para el Maestro',
      NombreArchivo: 'ESC_TB_05_historia',
      Idioma: 'Espanol',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '625',
      Nombre: 'Matemáticas Libro para el Maestro',
      NombreArchivo: 'ESC_TB_05_matematicas',
      Idioma: 'Espanol',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '626',
      Nombre: 'English Teacher´s Book',
      NombreArchivo: 'ESC_TB_05_english',
      Idioma: 'Ingles',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '627',
      Nombre: 'Geography Teacher´s Book',
      NombreArchivo: 'ESC_TB_05_geography',
      Idioma: 'Ingles',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '628',
      Nombre: 'History Teacher´s Book',
      NombreArchivo: 'ESC_TB_05_history',
      Idioma: 'Ingles',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '629',
      Nombre: 'Math Teacher´s Book',
      NombreArchivo: 'ESC_TB_05_math',
      Idioma: 'Ingles',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '630',
      Nombre: 'Science Teacher´s Book',
      NombreArchivo: 'ESC_TB_05_science',
      Idioma: 'Ingles',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '631',
      Nombre: 'Ciencias Naturales Libro para el Maestro',
      NombreArchivo: 'ESC_TB_06_ciencias_naturales',
      Idioma: 'Espanol',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '632',
      Nombre: 'Español Libro para el Maestro',
      NombreArchivo: 'ESC_TB_06_espanol',
      Idioma: 'Espanol',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '633',
      Nombre: 'Formación Cívica y Ética Libro para el Maestro',
      NombreArchivo: 'ESC_TB_06_formacion_civica_y_etica',
      Idioma: 'Espanol',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '634',
      Nombre: 'Geografía Libro para el Maestro',
      NombreArchivo: 'ESC_TB_06_geografia',
      Idioma: 'Espanol',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '635',
      Nombre: 'Historia Libro para el Maestro',
      NombreArchivo: 'ESC_TB_06_historia',
      Idioma: 'Espanol',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '636',
      Nombre: 'Matemáticas Libro para el Maestro',
      NombreArchivo: 'ESC_TB_06_matematicas',
      Idioma: 'Espanol',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '637',
      Nombre: 'English Teacher´s Book',
      NombreArchivo: 'ESC_TB_06_english',
      Idioma: 'Ingles',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '638',
      Nombre: 'Geography Teacher´s Book',
      NombreArchivo: 'ESC_TB_06_geography',
      Idioma: 'Ingles',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '639',
      Nombre: 'History Teacher´s Book',
      NombreArchivo: 'ESC_TB_06_history',
      Idioma: 'Ingles',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '640',
      Nombre: 'Math Teacher´s Book',
      NombreArchivo: 'ESC_TB_06_math',
      Idioma: 'Ingles',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '641',
      Nombre: 'Science Teacher´s Book',
      NombreArchivo: 'ESC_TB_06_science',
      Idioma: 'Ingles',
      Grados: '6',
      Suffix: 'th',
      Escolaridad: 'Elementary School',
    },
    {
      Id: '642',
      Nombre: 'Ciencias y Tecnología (Biología) Libro para el Maestro',
      NombreArchivo: 'JHS_TB_01_ciencias_y_tecnologia_biologia',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '643',
      Nombre: 'Formación Cívica y Ética Libro para el Maestro',
      NombreArchivo: 'JHS_TB_01_formacion_civica_y_etica',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '644',
      Nombre: 'Lengua Materna Español Libro para el Maestro',
      NombreArchivo: 'JHS_TB_01_lengua_materna_espanol',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '645',
      Nombre: 'Geography Teacher´s Book',
      NombreArchivo: 'JHS_TB_01_geography',
      Idioma: 'Ingles',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '646',
      Nombre: 'History Teacher´s Book',
      NombreArchivo: 'JHS_TB_01_history',
      Idioma: 'Ingles',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '647',
      Nombre: 'Math Teacher´s Book',
      NombreArchivo: 'JHS_TB_01_math',
      Idioma: 'Ingles',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '649',
      Nombre: 'Español Libro para el Maestro',
      NombreArchivo: 'JHS_TB_02_espanol',
      Idioma: 'Espanol',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '650',
      Nombre: 'Formación Cívica y Ética Libro para el Maestro',
      NombreArchivo: 'JHS_TB_02_formacion_civica_y_etica',
      Idioma: 'Espanol',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '651',
      Nombre: 'History Teacher´s Book',
      NombreArchivo: 'JHS_TB_02_history',
      Idioma: 'Ingles',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '652',
      Nombre: 'Math Teacher´s Book',
      NombreArchivo: 'JHS_TB_02_math',
      Idioma: 'Ingles',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '653',
      Nombre: 'Ciencias (Química) Libro para el Maestro',
      NombreArchivo: 'JHS_TB_03_ciencias_quimica',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '654',
      Nombre: 'Español Libro para el Maestro',
      NombreArchivo: 'JHS_TB_03_espanol',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '655',
      Nombre: 'Formación Cívica y Ética Libro para el Maestro',
      NombreArchivo: 'JHS_TB_03_formacion_civica_y_etica',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '656',
      Nombre: 'History Teacher´s Book',
      NombreArchivo: 'JHS_TB_03_history',
      Idioma: 'Ingles',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '657',
      Nombre: 'Math Teacher´s Book',
      NombreArchivo: 'JHS_TB_03_math',
      Idioma: 'Ingles',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '659',
      Nombre: 'Ética I Libro para el Maestro',
      NombreArchivo: 'HSC_TB_01_etica_I',
      Idioma: 'Espanol',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'High School',
    },
    {
      Id: '664',
      Nombre: 'Investigation Methodology Teacher´s Book',
      NombreArchivo: 'HSC_TB_01_investigation_methodology',
      Idioma: 'Ingles',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'High School',
    },
    {
      Id: '670',
      Nombre: 'Biología I Libro para el Maestro',
      NombreArchivo: 'HSC_TB_03_biologia_I',
      Idioma: 'Espanol',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'High School',
    },
    {
      Id: '675',
      Nombre: 'History of Mexico Teacher´s Book',
      NombreArchivo: 'HSC_TB_03_history_of_mexico',
      Idioma: 'Ingles',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'High School',
    },
    {
      Id: '687',
      Nombre: 'Probabilidad y Estadística Libro para el Maestro',
      NombreArchivo: 'HSC_TB_05_probabilidad_y_estadistica',
      Idioma: 'Espanol',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '688',
      Nombre: 'Geography Teacher´s Book',
      NombreArchivo: 'HSC_TB_05_geography',
      Idioma: 'Ingles',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '698',
      Nombre: 'English A1 Teacher´s Book',
      NombreArchivo: 'HSC_TB_A1_englsih_a1',
      Idioma: 'Ingles',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'High School',
    },
    {
      Id: '699',
      Nombre: 'English A2 Teacher´s Book',
      NombreArchivo: 'HSC_TB_A2_englsih_a2',
      Idioma: 'Ingles',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'High School',
    },
    {
      Id: '700',
      Nombre: 'English B1 Teacher´s Book',
      NombreArchivo: 'HSC_TB_B1_english_b1',
      Idioma: 'Ingles',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'High School',
    },
    {
      Id: '701',
      Nombre: 'English B2 Teacher´s Book',
      NombreArchivo: 'HSC_TB_B2_english_b2',
      Idioma: 'Ingles',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '702',
      Nombre: 'English C1 Teacher´s Book',
      NombreArchivo: 'HSC_TB_C1_englsih_c1',
      Idioma: 'Ingles',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'High School',
    },
    {
      Id: '704',
      Nombre: 'English A1 Teacher´s Book',
      NombreArchivo: 'JHS_TB_A1_englsih_a1',
      Idioma: 'Ingles',
      Grados: '1',
      Suffix: 'st',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '705',
      Nombre: 'English A2 Teacher´s Book',
      NombreArchivo: 'JHS_TB_A2_englsih_a2',
      Idioma: 'Ingles',
      Grados: '2',
      Suffix: 'nd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '706',
      Nombre: 'English B1 Teacher´s Book',
      NombreArchivo: 'JHS_TB_B1_english_b1',
      Idioma: 'Ingles',
      Grados: '3',
      Suffix: 'rd',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '707',
      Nombre: 'English B2 Teacher´s Book',
      NombreArchivo: 'JHS_TB_B2_english_b2',
      Idioma: 'Ingles',
      Grados: '4',
      Suffix: 'th',
      Escolaridad: 'Junior High School',
    },
    {
      Id: '708',
      Nombre: 'English C1 Teacher´s Book',
      NombreArchivo: 'JHS_TB_C1_englsih_c1',
      Idioma: 'Ingles',
      Grados: '5',
      Suffix: 'th',
      Escolaridad: 'Junior High School',
    },
  ];
}
